version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Test.Scopes.App/Dockerfile
    ports:
      - "8000:8000"
  api:
    build:
      context: .
      dockerfile: ./Test.Scopes/Dockerfile
    ports:
      - "5000:5000"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "!MyStrongPassword"
      ACCEPT_EULA: "Y"