version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Test.Scopes.App/Dockerfile
    depends_on:
      - api
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "8000:8000"

  api:
    build:
      context: .
      dockerfile: ./Test.Scopes/Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "5000:5000"

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "!MyStrongPassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
      
  e2e:
    image: cypress
    build: ./Test.Scopes.E2E
    container_name: cypress
    depends_on:
      - web
      - api
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Stage
    command: npx cypress run
    volumes:
      - ./Test.Scopes.E2E/cypress:/app/cypress
      - ./Test.Scopes.E2E/cypress.json:/app/cypress.json