version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "!MyStrongPassword"
      ACCEPT_EULA: "Y"
    container_name: db
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - internal

  api:
    image: api:latest
    build:
      context: .
      dockerfile: ./Test.Scopes/Dockerfile
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "5000:5000"
    healthcheck:
      test: curl --silent --fail http://api:5000/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - internal

  web:
    image: web:latest
    build:
      context: .
      dockerfile: ./Test.Scopes.App/Dockerfile
    container_name: web
    depends_on:
      api:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
    networks:
      - internal

  e2e:
    image: cypress
    build:
      context: .
      dockerfile: ./Test.Scopes.E2E/Dockerfile
    container_name: cypress
    depends_on:
      web:
        condition: service_started
    environment:
      - CYPRESS_baseUrl=http://localhost:80
    command: npx cypress run
    volumes:
      - ./Test.Scopes.E2E/cypress:/app/cypress
      - ./Test.Scopes.E2E/cypress.json:/app/cypress.json
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge